apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
        args:
        - "/bin/sh"
        - "-c"
        - "echo '<h1 style=\"color: blue; font-size: 24px; text-align: center;\">Merhaba, Ben Kader YILDIZ bu benim Httpd konteyner uygulamam!</h1>' > /usr/local/apache2/htdocs/index.html && httpd-foreground"
