# httpd-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
        args:
        - "/bin/sh"
        - "-c"
        - "echo 'Merhaba, Dünya!' > /usr/local/apache2/htdocs/index.html && httpd-foreground"
